server:
  port: 9098
spring:
  application:
    name: cloud-datasource-glue


eureka:
  client:
    serviceUrl:
      defaultZone:  http://127.0.0.1:8080/eureka/
  instance:
    metadata-map:
      test: wedatasphere

management:
  endpoints:
    web:
      exposure:
        include: refresh,info
logging:
  config: classpath:log4j2.xml